<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>

<?php if (isset($login) && $login) { ?>
    <h3> Спасибо за регстрацию: <?php echo $login ?></h3>
    <h4>Теперь ты можешь авторизоваться</h4>
<?php } ?>
<?php if (isset($error) && $error) { ?>
    <h5 style="color: red"><?php echo $error ?></h5>
<?php } ?>

<form action="/login" method="post"><br>
    <label for="">LOGIN OR EMAIL</label><br>
    <input type="text" name="username"><br>
    <label for="">PASSWORD</label><br>
    <input type="password" name="password"><br>
    <input type="submit" value="LOGIN">
</form>

</body>
</html>