<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
<?php if (isset($existEmail) && $existEmail) { ?>
    <h1>LOGIN ALREADY IS USED</h1>
<? } ?>
<?php if (isset($existLogin) && $existLogin) { ?>
    <h1>LOGIN ALREADY IS USED</h1>
<? } ?>
<form action="/register" method="post"><br>
    <label for="">LOGIN</label><br>
    <input type="text" name="login"><br>
    <label for="">EMAIL</label><br>
    <input type="email" name="email"><br>
    <label for="">PASSWORD</label><br>
    <input type="password" name="password"><br>
    <input type="submit" value="REGISTER">
</form>

</body>
</html>